---
- set_fact:
    fail2ban_conf_section: "{{ fail2ban_conf }}{{ fail2ban_conf_index|string if fail2ban_conf_index > 0 else '' }}"

- name: Configure fail2ban common option for sections
  when: fail2ban_confs[fail2ban_conf] is mapping
  notify:
    - Restart fail2ban
  community.general.ini_file:
    path: "{{ fail2ban_conf_path_overide }}"
    section: "{{ fail2ban_conf_section }}"
    option: "{{ fail2ban_conf_option }}"
    value: "{{ fail2ban_confs[fail2ban_conf].common[fail2ban_conf_option] }}"
    mode: "0600"
  loop: "{{ fail2ban_confs[fail2ban_conf].common|d({})|list }}"
  loop_control:
    loop_var: fail2ban_conf_option


- name: Configure conf specifique
  notify:
    - Restart fail2ban
  community.general.ini_file:
    path: "{{ fail2ban_conf_path_overide }}"
    section: "{{ fail2ban_conf_section }}"
    option: "{{ fail2ban_conf_option }}"
    value: "{{ fail2ban_conf_options[fail2ban_conf_option] }}"
    mode: "0600"
  loop: "{{ fail2ban_conf_options|list }}"
  loop_control:
    loop_var: fail2ban_conf_option
