---
- name: Configure local jails
  include_tasks: jails/conf.yml
  loop: "{{ fail2ban_jails_local|list }}"
  loop_control:
    loop_var: fail2ban_conf
  vars:
    fail2ban_confs: "{{ fail2ban_jails_local }}"
    # fail2ban_conf_path: /root/fail2ban/jail.local
    fail2ban_conf_path: /etc/fail2ban/jail.local

- name: Configure jails
  include_tasks: jails/conf.yml
  loop: "{{ fail2ban_jails|list }}"
  loop_control:
    loop_var: fail2ban_conf
  vars:
    fail2ban_confs: "{{ fail2ban_jails }}"
    # fail2ban_conf_base_path: /root/fail2ban/jail.d/
    fail2ban_conf_base_path: /etc/fail2ban/jail.d/
