---
- name: Configure local jail
  include_tasks: conf/conf.yml
  loop: "{{ fail2ban_jail_combine|list }}"
  loop_control:
    loop_var: fail2ban_conf
  vars:
    fail2ban_confs: "{{ fail2ban_jail_combine }}"
    # fail2ban_conf_path: /root/fail2ban/jail.local
    fail2ban_conf_path: /etc/fail2ban/jail.local

- name: Configure jail
  include_tasks: conf/conf.yml
  loop: "{{ fail2ban_jail_d_combine|list }}"
  loop_control:
    loop_var: fail2ban_conf
  vars:
    fail2ban_confs: "{{ fail2ban_jail_d_combine }}"
    # fail2ban_conf_base_path: /root/fail2ban/jail.d/
    fail2ban_conf_base_path: /etc/fail2ban/jail.d/
