---
# tasks file for fail2ban

- name: Validate fail2ban_jails_local variable
  ansible.utils.validate:
    data: "{{ fail2ban_jails_local }}"
    criteria:
      - "{{ lookup('template',  (role_path,'files/schemas/jails.local.yml.j2')|path_join) | from_yaml }}"
    engine: ansible.utils.jsonschema

- name: Validate fail2ban_jails variable
  ansible.utils.validate:
    data: "{{ fail2ban_jails }}"
    criteria:
      - "{{ lookup('template',  (role_path,'files/schemas/jails.yml.j2')|path_join) | from_yaml }}"
    engine: ansible.utils.jsonschema

# - name: Install fail2ban
#   package:
#     name: fail2ban
#     state: latest

# - name: Enable service
#   service:
#     name: fail2ban
#     enabled: true

- when: fail2ban_suppress_previous_conf
  block:
  - name: Find previous/other local fail2ban conf
    find:
      paths: /etc/fail2ban
      patterns: "*.local"
      hidden: true
      recurse: true
    register: fail2ban_previous_conf
  - name: Delete previous/other fail2Ban conf
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ fail2ban_previous_conf.files }}"

# - name: Copy file with owner and permissions
#   copy:
#     src: "/etc/fail2ban/{{ item }}.conf"
#     dest: "/etc/fail2ban/{{ item }}.local"
#     owner: root
#     group: root
#     mode: '0600'
#   with_items:
#     - jail
#     - fail2ban

# - import_tasks: jails.yml