---
- when: fail2ban_conf_options.name|d(fail2ban_conf_options.filter)|d(fail2ban_conf)==fail2ban_conf
  set_fact:
    fail2ban_conf_section: "{{ fail2ban_conf + (fail2ban_conf_index|string if fail2ban_conf_index > 0 else '') }}"
- when: fail2ban_conf_options.name|d(fail2ban_conf_options.filter)|d(fail2ban_conf)!=fail2ban_conf
  set_fact:
    fail2ban_conf_section: "{{ fail2ban_conf_options.name|d(fail2ban_conf_options.filter)|d(fail2ban_conf) }}"


- notify:
    - Restart fail2ban
  block:

    - name: Configure fail2ban common option for sections
      when: "fail2ban_conf_option != 'jail_specific'"
      community.general.ini_file:
        path: "{{ fail2ban_conf_path_overide }}"
        section: "{{ fail2ban_conf_section }}"
        option: "{{ fail2ban_conf_option }}"
        value: "{{ fail2ban_confs[fail2ban_conf][fail2ban_conf_option] if fail2ban_confs[fail2ban_conf][fail2ban_conf_option] is string or fail2ban_confs[fail2ban_conf][fail2ban_conf_option] is not iterable else fail2ban_confs[fail2ban_conf][fail2ban_conf_option]|join(',') }}"
        mode: "0600"
      loop: "{{ fail2ban_confs[fail2ban_conf]|d({})|list }}"
      loop_control:
        loop_var: fail2ban_conf_option

    - name: Configure conf specifique
      when: fail2ban_confs[fail2ban_conf].jail_specific|d(False)
      community.general.ini_file:
        path: "{{ fail2ban_conf_path_overide }}"
        section: "{{ fail2ban_conf_section }}"
        option: "{{ fail2ban_conf_option }}"
        value: "{{ fail2ban_conf_options[fail2ban_conf_option] if fail2ban_conf_options[fail2ban_conf_option] is string or fail2ban_conf_options[fail2ban_conf_option] is not iterable else fail2ban_conf_options[fail2ban_conf_option]|join(',') }}"
        mode: "0600"
      loop: "{{ fail2ban_conf_options|list }}"
      loop_control:
        loop_var: fail2ban_conf_option
